---
- name: Collect JUNOS Device Facts
  hosts: junos-r2
  connection: local
  gather_facts: no
  roles: 
    - Juniper.junos

  vars_prompt:
    - name: Username
      prompt: Username
      private: no
    - name: Password
      prompt: password
      private: yes

  tasks:
    - name:
      junos_get_facts:
        host: "{{ ansible_ssh_host  }}"
        user: "{{ Username  }}"
        passwd: "{{ Password  }}"

      register: output

    - name: show output
      debug:
        var: output

...
